### ISSUE TITLE
Upload to server and parse

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#22]
Upload transaction files to server storage and trigger data parse from there

**Comment by jonrandahl** [comment]
This is now working somewhat but is timing out (I think) on the larger datasets. 

I was pointed towards StackOverflow when I was posting my original question which turns out the issue was that the Transaction collection wasn't actually being created. Once I made it manually the smaller Save the Donkey's upload worked. 

When I tested the Sands data it worked for a few rows but then fell over with the following error: `Error: function crashed out of request scope Function invocation was interrupted.` I'm now looking at this now.
