### ISSUE TITLE
Fundraisers page load time

### ISSUE THREAD

**Issue by shramee** [NickBurneConsulting-GivePanel/givepanel#227]
Fundraisers page (table) takes loads to time to load.
Here's why we want to avoid saving it in the db if we need date range pickers.

# The issue

## Transactions data

![image](https://user-images.githubusercontent.com/11048263/54449656-a7e39880-4774-11e9-9da8-6c960dfc8ec3.png)

So if user selects dates 10 - 15...

![image](https://user-images.githubusercontent.com/11048263/54449743-d792a080-4774-11e9-9825-6ad891552870.png)

We just show 11 matching transactions... ✅  

## Fundraisers data

Now let's looks at fundraisers data...

![image](https://user-images.githubusercontent.com/11048263/54449855-1163a700-4775-11e9-8851-106ec84a09e3.png)

Now if users selects a date range...

![image](https://user-images.githubusercontent.com/11048263/54449972-4cfe7100-4775-11e9-9a36-6dbfedc7cc10.png)

We don't know what how much of green, blue and purple fundraisers we need to show... ❗️❗️❗️ 

# We need to generate fundraisers data on frontend

This is why this data needs to be generated on the frontend from transactions within that date range...

![image](https://user-images.githubusercontent.com/11048263/54449743-d792a080-4774-11e9-9825-6ad891552870.png)

Fundraiser | ... | Amount
-|-|-
Green | ... | 20
Pink | ... | 43
Blue | ... | 35
Purple | ... | 35

# Wait! What about resolving page load time?

Aah righty, performance improvements come from these 2 changes...
1. **We onlly deal with limited data** So in example above we only load and parse 11 transactions gaining quite some boost.
2. If we try to be clever and **use the same dates we have in dashboard for fundraisers** (which should make UX better anyway), we don't need to load any new data. 😮 Making it load as fast as (probs faster) than dashboard :grin:

**Comment by shramee** [comment]
Continues from #86

**Comment by nickburne** [comment]
Hey guys,

So I am happy for the default load of the dashboard, fundraiser table and
donations table to show the last 30 days. This means the fundraiser table
should be sorted by start date (newest at the top) and the donations table
by transaction date (newest at the top)

However in future we are going to want to give an option for users to
select “Lifetime” (eg all dates for all data). When they do this we will
want it to load as quickly as possible.

Hope this helps!

**Comment by jonrandahl** [comment]
My thoughts after reading through and listening to the recorded video are as such:

While I understand having a filtered dataset of transactions would indeed increase the speed it takes for the fundraisers to be dynamically on the fly, there's two issues now that I see:

1. When we get more data for a fundraiser that is already being stored in the DB, we will need to set the dynamic codebase to update that fundraiser on the fly which then adds more time to the rendering of the entire table anyway.

2. With your approach above the totals for fundraisers that have started earlier than the selected date, would be wrong, they would exclude the donations that had happened before, or after, the selected start date?

This would skew the results for the dataset being portrayed in green, purple, and blue:
![image](https://user-images.githubusercontent.com/39102/54463901-841c5480-476c-11e9-9265-81c0a4f82159.png)

If the fundraiser data was already in the database, which any that have been edited already are, this would mean that either

- We ignore any that don't "start" on the date chosen; 
- Or, we query the transactions-all collection for the campaignID for each fundraiser that falls within our dates and then query the fundraiser table to bring those back with their grand totals as they are;
- Or, we create a new field for each fundraiser which is a map of all transactions specific to a fundraiser but only contains the dates and amounts for each transaction which we then sum up between the requested dates and display that total instead of the grand total? (Kind of a merge of both our approaches @shramee! 👍 )

Nevertheless, I actually still think converting the fundraisers on the initial transaction upload is the right place to do it as then the only thing we're doing on the actual fundraisers page is portraying that already transformed data without having to do the transformations on the fly.

Happy to discuss this further if anyone has more to add or refute, please share if you have more ideas as well!

Kindest regards, and enjoy the weekend nonetheless!

Jon
