### ISSUE TITLE
Labels not updating in rows when set in fundraiser details card

### ISSUE THREAD

**Issue by nickburne** [NickBurneConsulting-GivePanel/givepanel#251]
On staging - Pancreatic Cancer UK

**Comment by nickburne** [comment]
You can see it go wrong in the last 10 sec of this video https://www.useloom.com/share/3fa4916e17f545a3afc10e16f4fe1397

**Comment by nickburne** [comment]
@jon-humphrey - so nearly did the video but can't do it without working labels.

**Comment by jonrandahl** [comment]
Okay, as far as I can tell the labels not updating in the row is because the data is already set there - not like it was before when it was an object in and of itself; it’s either with Shramee’s `GlobalDateComponent` or with Tiago’s moving that specific data into a state bound object instead. I will have to liaise with them both to work this one out.

if you choose a label in fundraiser details and then reload the page the “new” label is displayed.

Will update again in the morning.

**Comment by jonrandahl** [comment]
@shramee we've checked through the code with @HelloTiago for the labels to be applied to the row and while they are still being saved to the database and updating in the card details, we have somehow lost the watch on the data with it coming from the GlobalDatePicker? 

Please get in touch as soon as possible to discuss this as I can explain what we've tested and how we've arrived at this conclusion?

**Comment by shramee** [comment]
This is now fixed (finally!) 😅
